import time
from System.SlowTypeFunction import slowType
#------------------------------------------------------------------------------------------------------------------
#Invoice Creator
def invoice():
  message = ("Thank you for your business!")
  slowType("Welcome to T.E.S.S Invoice Creator vRPIos!", .02)
  time.sleep(1)
  companyName = input("Please enter the name of your company: ")
  time.sleep(1)
  companyAddress = input("Please enter the address of your company: ")
  time.sleep(1)
  product1 = input("Please enter the first product: ")
  time.sleep(1)
  product1price = input("Please enter the cost of this product: ")
  time.sleep(1)
  product2 = input("Please enter the second product: ")
  time.sleep(1)
  product2price = input("Please enter the cost of the second product: ")
  time.sleep(1)
  product3 = input("Please enter the third product: ")
  time.sleep(1)
  product3price = input("Please enter the cost of the third product: ")
  time.sleep(1)
  print(" ")
  print("Creating Invoice...")
  time.sleep(1)
  print(" ")
  print(" ")
  print(" ")
  print('*' * 50)
  print('\t\t{}'.format(companyName.title()))
  print('\t\t{}'.format(companyAddress.title()))
  print('=' * 50)
  print('\tProduct Name\tProduct Price')
  print('\t{}\t\t£{}'.format(product1.title(), product1price))
  print('\t{}\t£{}'.format(product2.title(), product2price))
  print('\t{}\t\t£{}'.format(product3.title(), product3price))
  print('=' * 50)
  print('\t\t\tTotal')
  total = product1price + product2price + product3price
  print('\t\t\t£{}'.format(total))
  print('=' * 50)
  print('\n\t{}\n'.format(message))
  print('*' * 50)
  print(" ")
  print(" ")
  print(" ")
invoice()